# Generated by Django 5.1.4 on 2024-12-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_schedule',
            field=models.DateTimeField(),
        ),
    ]
